#
# Simple development makefile
#

#
# add more flags here,
# but don't remove the "+="
#
CFLAGS += -std=c99 -Werror -O2 -g -Wall #-Wsign-compare -Wfloat-equal -Wformat-security #-Werror
CPPFLAGS +=
LDFLAGS +=


all: fbpaint-mmap

clean:
	-rm -f fbpaint-mmap

install:


.PHONY: all install clean

# end of development makefile
