#!/bin/sh

cat /etc/issue

# redirect error messages to /dev/null to suppress the error message if PROC is
# disabled in the kernel
mount -t proc proc /proc 2>/dev/null
mount -t sysfs sys /sys


export PATH=$PATH:/sbin:/usr/bin:/bin

modprobe driver-gamepad
mknod /dev/pad c 42 0

exec /usr/bin/game
exec /bin/sh
